import{i as u,g as p,c as f,q as m,o as g,a as y,b,s as v,d as h,e as S,f as w}from"./assets/vendor-79bf1253.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const A=document.querySelector(".gallery"),L=document.querySelector(".form"),q={apiKey:"AIzaSyCsA2GGOUbgQvviHSwmuoNUYnbKV6S1Sa4",authDomain:"imageboard-v01.firebaseapp.com",projectId:"imageboard-v01",storageBucket:"imageboard-v01.appspot.com",messagingSenderId:"436664988683",appId:"1:436664988683:web:e31047700b07fc4ada430e"};u(q);const i=p(),c=f(i,"posts"),d=m(c,g("createdAt","asc"));L.addEventListener("submit",O);async function O(o){o.preventDefault();const{value:s}=o.currentTarget.elements.post;s.trim()&&(await P(s),o.target.elements.post.value="")}async function l(){const o=await h(d);let s=[];o.docs.forEach(n=>{s.push({...n.data(),id:n.id})}),E(s)}y(d,l);async function P(o){await b(c,{title:o,date:new Date().toString().substring(0,24),createdAt:v()})}async function D(o){const s=S(i,"posts",o);await w(s)}function E(o){const s=o.map(({id:r,title:e,date:t})=>`
      <li class="gallery-item" id="${r}">
        <div class="title-wrapper">
          <p><b>Anonymous</b> ${t}</p>
          <button class="delete-btn">del</button>
        </div>
        <p class="item-text">${e}</p>
      </li>`).join("");A.innerHTML=s,document.querySelectorAll(".delete-btn").forEach(r=>{r.addEventListener("click",e=>{const t=e.target.parentNode.parentNode;D(t.getAttribute("id")),t.remove()})})}l();
//# sourceMappingURL=commonHelpers.js.map
